### ISSUE TITLE
敵を管理するツールを作成  

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#10]
敵の種類と武器の種類を自由に指定でき、リストが出来るツールをお願いしたい。

**Comment by matsumoto36** [comment]
実装しました。
Unity内でできるようになりました
大まかな流れとしては、右クリックメニューからUnit -> Create Enemy Dataで作成し、
各種情報を入力する流れです。

現状フォルダでまとめているだけなので、リストにはなっていないですが、見づらかったら私までお願いします。ということでいったんcloseします。
