### ISSUE TITLE
武器の実装

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#12]
デザインに関してはアセットを用意する。 
システムは以下の一覧を参考に実装して欲しい
各ステータスやパッシブ効果の数値ははUnity上で変更できるように実装
武器  
１.銃　　　　　ビーム弾を発射する  
　パッシブ：連射力上昇

２.ビーム銃　　チャージ時間を有して長いビーム発射  　
※チャージ時間と発射時間はレベルデザインによって可変したい  
　パッシブ：HP上昇、移動速度低下

３.剣　　　　　相手に近づいて斬る。  
　パッシブ：移動速度増加、攻撃力微上昇

４.グレポン　　爆弾を飛ばして着弾したらその周辺に、範囲ダメージ  
　パッシブ：攻撃力上昇、連射力低下

５.回復ビーム　味方を回復できるビームを発射できる武器
　パッシブ：移動速度低下、HP低下

パッシブ効果はもう片方のスロットの武器にも適用される。
よってパッシブ効果は重複するように実装して欲しい

※補足
武器は左クリックで発射
２スロット目の武器は予め内部的の保持しておき、
右クリックで使っている武器と交換できるようにする。
武器の連射速度も外から可変できるようにして欲しい

**Comment by matsumoto36** [comment]
# 実装完了しました
遅くなってしまい申し訳ありません
## 実装内容と補足
### 各武器の実装(以下補足)
- 各種武器・弾のモデル変更可
- 回復ビームはビームを基に実装
- 剣の攻撃と判定はキャラクタモーションに依存します

### パッシブ効果について
現在パッシブ効果で変更できるパラメータ(倍率)は以下の通りです
- HPの最大値(HP、増えた分だけ回復)
- 動く・回転する速度(MoveSpeed)
- 武器の攻撃力(Power)
- 武器の撃つ・振る速度(AttackSpeed、近接はモーションのスピードも速くなります)

パッシブ効果は各武器についているものを、キャラクタで合計したものを最終的に適用しています
(例)
武器1にHP+50%、MoveSpeed+0%、Power+20%、AttackSpeed+0%
武器2にHP+25%、MoveSpeed+20%、Power+0%、AttackSpeed+50%
適用される効果はHP+75%、MoveSpeed+20%、Power+20%、AttackSpeed+50%になります

パッシブ効果はUnityのインスペクタ上からいつでも変更できるようにしてあります
変更方法は2種類有ります
- Playerから合計値を変更(※ 値が再計算で変わってしまう恐れがありますので一時的にです)
- 各武器から変更(※ 変更後はPlayerの合計値の下のボタン"パッシブ効果を更新"を押してください)

### 武器交換について
補足通り、左クリックで発射、右クリックで交換になります
ただし、交換速度、交換する瞬間(武器が入れ替わるとき)はモーション依存になります

その他詳しい情報は口頭のほうが早いと思いますので、松元までお願いします。以上です
