### ISSUE TITLE
カメラの挙動

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#13]
カメラは各プレイヤーのいる位置によって視野範囲を広げたり狭めたり出来るようにする。
ソロプレイの場合はカメラは固定距離にする。

**Comment by matsumoto36** [comment]
引き継ぎました。以後は私が実装する予定です。

**Comment by matsumoto36** [comment]
実装しました。各パラメータはUnity上で変更することができます。

必ずしも完全に見下ろしで使用しなければならないわけではないので、
カメラを回転する場合は、オフセットで調整してください。

その他わからない点があれば松元までお願いします。
