### ISSUE TITLE
ギミック(タレット)のシステムの実装

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#19]
アセットはこれを使用予定。
https://www.assetstore.unity3d.com/jp/#!/content/102642
タレットの一定範囲内に入ったらそのプレイヤーの方向に向いて
銃弾を撃ってくるシステムの実装
複数のプレイヤーが範囲内に入った時は、
その中の一番近いプレイヤーに方向を向くようにして欲しい

**Comment by matsumoto36** [comment]
実装しました。
武器はプレイヤーと同じように持たせる感じになりました。

各種パラメータでカスタムできるようにしておきました
・検知半径
・視野角(度)
・検知範囲外で攻撃されたときに振り向くかどうか
・使用する武器(既存の武器種はすべて対応)

アセットは適用していませんが、モデルさえあれば柔軟に対応できます。

現状、攻撃しているターゲット以外のプレイヤーに攻撃されてもヘイトが向かないので、
変えたい場合は松元までお願いします。
