### ISSUE TITLE
敵AIの補足事項

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#23]
現状の敵AIは近くのプレイヤーに対して持続的に弾を撃ち続ける状態になっているので、
敵の武器の使用頻度を断続的に使用するように変更し、敵が弾を撃つのを少し休む、
という挙動になるようにして欲しい

**Comment by matsumoto36** [comment]
タレットの方も必要とのことなので作業に参加しました。
敵・タレットの共通処理をEnemy.csに記述しましたので、EnemyAI.csで動作を変更する必要はありません。(変更してもいいですよ)
敵が攻撃休止中かどうかを取得したい場合は、isRestを取得してください。

**Comment by matsumoto36** [comment]
機能を実装しましたので、Pullしてください。
