### ISSUE TITLE
耐久卵機能の実装  

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#4]
・体力が一定以下になった時、任意のタイミングで耐久卵に篭り  
　　　無敵状態になれる。ただしデメリットがあり、  
　　　無敵解除後数秒かは受けるダメージが増加する（耐久卵から孵化したてのため）  
　　　回数無制限

**Comment by matsumoto36** [comment]
実装しました。
キーの指定がなかったので、現状はEキーor Aボタンで実装してあります。
見た目の調整はまだしていないので、顔がはみ出たりしていますが...

Unity上でこういった不変的なデータ弄れるといいなぁと思ったので、
弄れるようにデータセット作っておきました。詳細は松元までお願いします。
