### ISSUE TITLE
プレイヤー(+敵の)システムの実装 

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#5]
・HPと攻撃力と移動速度を実装  
　・HPは可視化、攻撃力、移動速度は内部ステータスとして実装  
　・プレイヤーは一定経験値を取得するとレベルアップ出来るように実装  
　　　レベルアップに必要な経験値＝前のレベルでレベルアップに必要だった経験値×1.1  
　　　パラメータの上昇率　攻撃力：現ステータスの1.5倍　HP：現ステータスの1.25倍(仮定)    
　・プレイヤーは２スロットの中に自由に武器を装備できるように実装  
　・敵には倒した後にプレイヤーに経験値が入るように実装して欲しい  
　・更にマルチプレイ時には、複数人で敵を倒した時に与えた合計ダメージの割合によって
　　経験値を割り振るようにする。
　・回復武器では回復した値によって経験値を取得できるようにする

**Comment by matsumoto36** [comment]
実装しました。
武器等のデータは基本CSVデータを編集してパラメータを反映していく流れになりますが、
Unityでも一時的に改変できます。(プレイヤーのデータはUnityで変更したほうが早いと思いますので、読み込み機能は未検討です)

敵もほぼプレイヤーと同じように行動でき、装備した武器で攻撃となります。(武器を隠すこともできます)

取得経験値の計算が小数点以下の計算に対応したため、正確に敵を倒した時の経験値を割り振るすることができ、また回復したときの経験値も倍率を掛けて計算することができます

例 : パワーが10のレーザーで味方を照射したときの取得経験値(経験値倍率 0.5)
パワー10 -> 一秒間で10回復するので、取得経験値は5EXP/秒となります。

その他詳しい情報は(ry
