### ISSUE TITLE
敵＆プレイヤーのアニメーションの実装

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#7]
・敵＆プレイヤーのアニメーションの実装  
　(アセットで拾ってきた物の解読)

**Comment by matsumoto36** [comment]
入っている分は実装しました。

実装したいアニメーションがないもので、
・デフォルトで入っている場合 -> 3DCGソフトで追加 or 他モデルからのリターゲット
・デフォルトで入っていない場合 -> Unityで作る

必要があるので、その周りの指示等をお願いします。

**Comment by matsumoto36** [comment]
近接武器・切り替えのモーションを実装しました。
