### ISSUE TITLE
敵AIの実装  

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/LetterProduct2017#9]
・敵は各プレイヤーの中で一番近いプレイヤーに向かって進行するように実装  
　一定範囲内に入ると一定間隔で攻撃出来るように  
　相手の攻撃の種類は此方の武器と同じなので、  
　武器ごとに射程範囲を決めてもらえると良い  
　早さを可変出来るように出来ると敵の幅が増えると思うのでお願いしたい。    

　敵のAIは3種類、上から順にできるところまで実装する  
　[基本タイプ]  
　・検知範囲内に入るとそのプレイヤーに向かって動き出す  
　・攻撃範囲内に入ると攻撃する    

　[近接タイプ]  
　・基本タイプにステップ攻撃を追加。ステップ攻撃範囲内に入ると  
　一気に距離を詰めて攻撃範囲内まで寄ってくる。    

　[2武器タイプ]  
　・近接タイプに遠距離武器を持たせたもの。  
　ステップ攻撃範囲内に入るまでは、見えていれば手持ちの遠距離武器で攻撃する

**Comment by matsumoto36** [comment]
多分やってない(終わった)と思いますので、閉じておきますね
